# Generated by Django 5.0.4 on 2025-07-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'abbreviation')},
            },
        ),
        migrations.CreateModel(
            name='ClassRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.schools')),
            ],
            options={
                'unique_together': {('school', 'class_level', 'room')},
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('LGBTQ+', 'L')], max_length=10)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classrooms')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('LGBTQ+', 'L')], max_length=10)),
                ('class_room', models.ManyToManyField(to='apis.classrooms')),
            ],
        ),
    ]
